### ISSUE TITLE
Improve testing documentation

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1323]
I followed https://github.com/cryptoadvance/specter-desktop/blob/master/DEVELOPMENT.md#how-to-run-the-tests and `pytest` results in 
```tests/conftest.py:10: in <module>
    import docker
E   ModuleNotFoundError: No module named 'docker'
```

Then I ran `python3 -m pytest`  and I get lots of errors of the following form:

```
E           cryptoadvance.specter.specter_error.SpecterError: Could not find debug.log at /tmp/specter_bitcoin_regtest_plain_datadir_9r4in63q/regtest/debug.log. Is that directory even existing?

src/cryptoadvance/specter/process_controller/node_controller.py:440: SpecterError
```
and the summary shows:
```
ERROR tests/test_node.py::test_Node_elm - cryptoadvance.specter.specter_error.SpecterError: Could not find debug.log at /tmp/specter_elements_regtest_plain_datadir_2x124u0b/regtest/debug.log. Is that dire...
======================================================================= 4 failed, 65 passed, 3 skipped, 4 warnings, 30 errors in 4.45s ========================================================================
```

How can I get the tests to run successfully?

**Comment by k9ert** [comment]
Oh, sorry for the bad experience. Interesting enough, i couldn't reproduce the docker-issue. `pip3 install docker` should solve it but i think we removed the docker-requirement from test-requirements as this dependency is quite cvomplicated to install on some platforms and i'm more or less the only one using docker.
Anyway the second issue is due to the support of docker in testing and to adding liquid without taking care for manual testing on dev-laptops.

So here is an explanation in list-form:
* Development is only supported on Mac and Linux, at least on Windows you're pretty much on your own as it's difficult to support/document it
* Everyone needs a bitcoin and a liquid node to test
* Before Liquid was needed, docker was still supported but in the meantime i guess we should remove the support completely as it's only creating confusion
* Compiling and/or installing Bitcoin Core should be something a Dev should be able to do. However we have some support for that:
  * `./tests/install_bitcoind.sh --bitcoin binary` will install bitcoind in tests/bitcoin
  * `./tests/install_bitcoind.sh --bitcoin compile` will compile bitcoind in tests/bitcoin
  * `./tests/install_bitcoind.sh --elements compile` will compile elements in tests/elements
  * However feel free to use any `elementsd` / `bitcoind` as long as it is on the path, it will used by the test-framework

I'll soon fix this.

**Comment by relativisticelectron** [comment]
Even after running `./tests/install_bitcoind.sh --bitcoin compile`  and `./tests/install_bitcoind.sh --elements compile`  ,  `python3 -m pytest`  results in:
```
ERROR tests/test_wallet_manager.py::test_multisig_wallet_backup_and_restore[False] - cryptoadvance.specter.specter_error.SpecterError: Could not find debug.log at /tmp/specter_bitcoin_regtest_plain_datadi...
ERROR tests/test_liquid_rpc.py::test_LiquidRpc - cryptoadvance.specter.specter_error.SpecterError: Could not find debug.log at /tmp/specter_elements_regtest_plain_datadir_bgbjh60w/regtest/debug.log. Is th...
ERROR tests/test_node.py::test_Node_elm - cryptoadvance.specter.specter_error.SpecterError: Could not find debug.log at /tmp/specter_elements_regtest_plain_datadir_bgbjh60w/regtest/debug.log. Is that dire...
======================================================================= 4 failed, 65 passed, 3 skipped, 4 warnings, 30 errors in 4.44s ========================================================================
```

**Comment by relativisticelectron** [comment]
With the changes from https://github.com/cryptoadvance/specter-desktop/pull/1326 I get the test result after running `pytest`
```
- Docs: https://docs.pytest.org/en/stable/warnings.html
====================================================================== short test summary info =======================================================================
FAILED tests/test_cli_bitcoind.py::test_elements - AssertionError: assert 1 == 0
ERROR tests/test_managers_node.py::test_NodeManager[False] - cryptoadvance.specter.rpc.RpcError: Request error: Compiled without sqlite support (required for descr...
ERROR tests/test_liquid_rpc.py::test_LiquidRpc - cryptoadvance.specter.rpc.RpcError: Request error: Compiled without sqlite support (required for descriptor wallets)
ERROR tests/test_node.py::test_Node_elm - cryptoadvance.specter.rpc.RpcError: Request error: Compiled without sqlite support (required for descriptor wallets)
============================================ 1 failed, 96 passed, 2 skipped, 198 warnings, 3 errors in 137.76s (0:02:17) =============================================
```
