### ISSUE TITLE
New feature: select scan startpoint

### ISSUE THREAD

**Issue by inpharmaticist** [cryptoadvance/specter-desktop#137]
Not sure if this is a current feature, but it would be nice if you could select a block height or date to start the scan for an existing wallet to save time.

**Comment by ben-kaufman** [comment]
Hi @inpharmaticist, this is already possible. Just select the wallet that you want to rescan in the sidebar, then click on the "Settings" tab. There you'll have a label saying "Rescan blockchain from block:", where you can see an input with block number `481824` and a "Rescan" button next to it.

<img width="942" alt="Screen Shot 2020-05-21 at 21 19 50" src="https://user-images.githubusercontent.com/10667901/82591968-d050f900-9ba8-11ea-8bbf-08b9b8f49574.png">

**Comment by inpharmaticist** [comment]
oh, nice. Thanks!

**Comment by ChristopherA** [comment]
I note that both FullyNoded2 (@Fonta1n3) and Spectre currently leverage option block height metadata. The UR spec (@wolfmcnally) for keys has the optional birthday for cryptographic which is unix days since, not block height, as cryptographic seeds can used for more purposes than Bitcoin. Is it easy to convert a block height to a unix days since (and visa versa)?

-- Christopher Allen

**Comment by ben-kaufman** [comment]
@ChristopherA I think converting a block height to unix days since is trivial, but the reverse is more tricky. There are APIs that could provide that information, which we can then test against the local full node to verify. But if we wish to do that using only the user's node then the best option I have in mind for that is a binary search for the closest block to that time.
