### ISSUE TITLE
Testnet on Windows creates new testnet3 folders (Specter v1.6.0)

### ISSUE THREAD

**Issue by B-396** [cryptoadvance/specter-desktop#1378]
After closing and reopening Specter Desktop connected to a local testnet node on Windows, Specter cannot find the wallet files anymore. The problem seems to be that a new testnet3 folder is created every time (e.g. .specter\nodes\specter_testnet\.bitcoin-testnet\testnet3\testnet3\testnet3\testnet3\testnet3\wallets\specter\<wallet name>). This also leads to a new IBD.

**Comment by k9ert** [comment]
Confirmed to not be an issue on Linux. I guess this is happening because the the slash (/) here:
https://github.com/cryptoadvance/specter-desktop/blob/master/src/cryptoadvance/specter/internal_node.py#L68

I guess simply removing the slash in this line (and the other three lines) would fix this issue.
