### ISSUE TITLE
Specter not showing taproot derivation on Trezor

### ISSUE THREAD

**Issue by Quenos** [cryptoadvance/specter-desktop#1506]
Using Trezor model One firmware 1.10.4 and Specter 1.7.1 I cannot add a key for the taproot derivation.

How can I unlock this?

**Comment by k9ert** [comment]
According to @stepansnigirev , taproot is marked as experimental and only confirmed to be working in the hot-wallet and in Specter-DIY.
It might also work in Trezor and at least adding the key should not be the issue (even though that's the trivial step):
* Choose your device or create a new one
* "Add more keys" (if you add them to an existing one)
* "Edit"
* "Add custom derivation"
* choose `m/86h/0h/0h` and a reasonable purpose
* "Add"
* continue as usual

However, that's AFAIK as far as you can get.

**Comment by stepansnigirev** [comment]
Taproot PSBT fields are not implemented in Bitcoin Core yet, so we need to wait for https://github.com/bitcoin/bitcoin/pull/22558 and for HWI release with taproot support as well.
Until then taproot support is limited to Bitcoin Core Hot wallet that can sign even without derivations in the PSBT, and to Specter-DIY where we abused standard bip32 derivation fields (that's why taproot support in DIY is marked as experimental - it will change as soon as we add support for taproot fields).

**Comment by michaelfolkson** [comment]
Personally I'd encourage those who are able (that definitely includes you @stepansnigirev!) to review/test https://github.com/bitcoin/bitcoin/pull/22558 and post a comment describing whatever reviewing/testing they've done.

It is marked as high priority for review in the Core repo so it would definitely be nice to get it merged and the more review it gets the closer it gets to being merge-able.

**Comment by cryptagoras** [comment]
Unless I'm mistaken this was unblocked with the release of Bitcoin Core v24.
It seems the merge of #1837 did the majority of the work, is there more work needed for enabling it with Trezor? (I see it disabled on the latest v2 version)

**Comment by k9ert** [comment]
We recently enabled taproot support for trezor in #2295. However, that did not made it to the release. We'll soon do a new release where this will be in.

**Comment by k9ert** [comment]
This should be fixed now with `v2.0.1`.
https://twitter.com/SpecterWallet/status/1640840642220769280
