### ISSUE TITLE
`BaseConfig` not reading `SPECTER_API_ACTIVE` envvar properly

### ISSUE THREAD

**Issue by 84adam** [cryptoadvance/specter-desktop#1521]
See also: Issue #1430 -- This is still causing issues for me with version 1.7.2:

For some reason it seems the `BaseConfig` is not reading the `SPECTER_API_ACTIVE` envvar properly here: https://github.com/cryptoadvance/specter-desktop/blob/master/src/cryptoadvance/specter/config.py#L41

I confirmed on the command line with `echo $SPECTER_API_ACTIVE` that this is set to `True`. And I restarted the server/daemon multiple times, however, it doesn't seem to pick up on the envvar.

Manually changing it to `class BaseConfig(object):` ... `SPECTER_API_ACTIVE = True` resolved the issue for me.

_Originally posted by @84adam in https://github.com/cryptoadvance/specter-desktop/issues/1430#issuecomment-964470351_

---

When I run the test suggested by @k9ert I get nothing back, even with the above changes:

- `# ps aux | grep specter` # check PID of specter process
- `# ps e -p <PID> | sed 's/ /\n/g' | grep API`
- `> ` (no hits for 'API')

It seems `_get_bool_env_var("SPECTER_API_ACTIVE", "False")` is failing silently to grab the envvar value, although, as mentioned, I know for a fact that `SPECTER_API_ACTIVE` is set to `True`.

**Comment by k9ert** [comment]
The problem is, that i can't reproduce your issue. This is how i tested:
* I'm setting `export SPECTER_API_ACTIVE=True` (Ubuntu Linux)
* I'm starting the server like this: `python3 -m cryptoadvance.specter server --config ProductionConfig --debug `
* I see this in the logs:
```
[2022-01-06 13:50:22,870] INFO in server: Initializing Controller ...
[2022-01-06 13:50:22,882] INFO in wallet_manager: Getting loaded wallets list from Bitcoin Core
[2022-01-06 13:50:22,882] INFO in wallet_manager: Wallet already loaded in Bitcoin Core. Initializing mymultisig Wallet object
[2022-01-06 13:50:23,180] INFO in server: Initializing REST ...
[2022-01-06 13:50:23,215] WARNING in _internal:  * Debugger is active!
[2022-01-06 13:50:23,216] INFO in _internal:  * Debugger PIN: 267-182-335
```
`Initializing REST ...` is key here as you can see in https://github.com/cryptoadvance/specter-desktop/blob/master/src/cryptoadvance/specter/server.py#L175-L176

Here us the output for checking the env-var:
```
➜  specter-desktop git:(master) ✗ ps uax | grep specter                                                      
kim        19392 14.8  0.3 192748 63488 pts/0    Sl+  13:53   0:01 python3 -m cryptoadvance.specter server --config ProductionConfig --debug
[...]
➜  specter-desktop git:(master) ✗ ps e -p 19392 | sed 's/ /\n/g' | grep API
SPECTER_API_ACTIVE=True
➜  specter-desktop git:(master) ✗
```
I can't judge where your issue is but if you can't verify that you've set your Envvar according to my test described, it's definitely an issue on your system.
The workaround would be to copy config.py and place it to some other package in your pyEnv. Make the changes you would like to see. Let's assume your config.py is located in `mypackage.config`. Then you should be able to use your homegrown config like `python3 -m cryptoadvance.specter server --config mypackage.ProductionConfig --debug`

**Comment by 84adam** [comment]
The issue was that the envvar was not being propagated to the service started via systemctl (systemd daemon).

I had to add this line at the end of the `[Service]` block in `/lib/systemd/system/specter.service`:

`Environment="SPECTER_API_ACTIVE=True"`

Then run `systemctl daemon-reload` and `systemctl restart specter.service`. And now it works.

Reference: https://serverfault.com/questions/413397/how-to-set-environment-variable-in-systemd-service
