### ISSUE TITLE
Can't start the QR scanner! TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia')

### ISSUE THREAD

**Issue by Bridsrnotreal** [cryptoadvance/specter-desktop#1602]
when trying to upload an existing wallet

New umbrel node
MacOS
Tried on Chrome, Safari (mobile and desktop)

On local network, not accessing via tor link.

Error: 
`Can't start the QR scanner! TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia')`

**Comment by k9ert** [comment]
This is probably due to not using https. See this issue for details:
https://github.com/getumbrel/umbrel/pull/400#issuecomment-757131821

TL;DR you can set a flag on chrome to deactivate that security-rule. Another alternative is to go over to umbrel and push them to provide specter with a self-signed-cert.
Closing this issue for now.
