### ISSUE TITLE
UI: Whitelisted Addresses

### ISSUE THREAD

**Issue by Minituff** [cryptoadvance/specter-desktop#1604]
When sending crypto I have a large fear of sending to the wrong address. I make sure to check (and triple check) each address before I send BTC.  I love that most exchanges will let you create a whitelist of addresses that you know are correct, that way you can be certain there is no typo in the address.

A simple whitelist that requires your password to edit would be a great quality of life feature that may help reduce some of this anxiety. Furthermore, it may help stop a clipboard attack where you actually paste the wrong receive address. 

If a feature like this was implemented, then I could send a test amount of BTC and ensure it arrives before actually sending any large amounts of crypto to the same address.

**Comment by relativisticelectron** [comment]
**Pro**: I agree with you that sending to an address is a tense moment.
**Con1**: A whitelist encourages reusing addresses, which is bad practice (privacy vice).
**Con2**: While it may prevent clipboard attacks, a malware could simply swap out the whitelist file, and next time you start specter it has a malicious whitelist. Which is in some sense even worse than a clipboard attack, because the whitelist gives a false sense of security.

**Comment by Minituff** [comment]
I was not aware of the `Known address` feature. This accomplishes what I was looking for. Thank you!

**Comment by relativisticelectron** [comment]
> I was not aware of the `Known address` feature. This accomplishes what I was looking for. Thank you!

Great that I could help. `Known address` is just a label, you can give any label to any address appearing in specter.

If your issue is solved, can you please close the issue?
