### ISSUE TITLE
Chore: Upgrade install_noded.sh to handle bitcoin versions >= 22.0

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1701]
Problem: https://github.com/cryptoadvance/specter-desktop/blob/0f530667264176e80aa06eb944a23cf3e8672378/tests/install_noded.sh#L96  should not be excecuted for versions >=22.0 .

This script is also used in the CI pipeline:  https://github.com/cryptoadvance/specter-desktop/blob/0f530667264176e80aa06eb944a23cf3e8672378/.cirrus.yml#L15
And  after this issue is solved, one could upgrade the version in `pytest.ini`

**Comment by k9ert** [comment]
I don't understand the issue here. I just installed `v23` without any issue. The relevant part is also this:
https://github.com/cryptoadvance/specter-desktop/blob/master/tests/conftest.py#L158-L161

The reason for that line is the difference core makes with uploading their binaries (23.0) vs. the version that binary returns via `getnetworkinfo()["subversion"]` ( `  "subversion": "/Satoshi:23.0.0/",` )

**Comment by relativisticelectron** [comment]
Ok. I was mistaken. I thought 
https://github.com/cryptoadvance/specter-desktop/blob/8e6c374c110aca9639aa4b6cc3f3e2d5b0605a6e/pytest.ini#L4
should actually have `v22.0`   and that would cause an issue in [install_noded](https://github.com/cryptoadvance/specter-desktop/blob/0f530667264176e80aa06eb944a23cf3e8672378/tests/install_noded.sh#L96).

But if `v22.0.0` is actually the correct version number, then everything is good.

**Comment by k9ert** [comment]
In the first place, addopts was used to CHECK that the right version is installed within the test-framework. That's why it's still having three digits.
Just afterwards i reused the version in the install_noded, and there i needed to cut down one digit to make the download work.
