### ISSUE TITLE
SPV Option

### ISSUE THREAD

**Issue by Odellian** [cryptoadvance/specter-desktop#1792]
**Feature Request**
I have a couple Foundation Passports in route to some family members.  I would love to introduce them to this wallet if SPV was an option and then I could recommend Swan DCA.  My opinion is that it's a good way to onboard newbs and keep them in the Specter space, but what do I know about business.  Apple and Microsoft do it with educational discounts, right?  So, I'm thinking it must pay off.   

Is there a way I can shepherd them, via a link to my node.  We don't live in the same location so they won't be able to access it from my LAN.  Tor link with a user name and password??? 

Keep kicking ass! And point me towards the tip jar, so I can drop you some sats.

**Comment by k9ert** [comment]
There are different way to do this:
* If the use specter on there laptop/desktop, they can use an internal pruned-node but i guess that's what you want to avoid
* If you want to provide your specter to them via tor, you should probably do that via a node-implementation like raspiblitz. However, depending on the hardware-wallet, it might only be a watch-only solution as tor does not allow camera (and i'm not so sure about the hwi-bridge)
* There is also something new coming up: [spectrum](https://github.com/cryptoadvance/spectrum/) will allow specter to connect to a electrum-node. However, this is currently in heavy development. If you're tech-savy, you can try to use that now, but that doesn't help for the original problem: Should be usable for non-tech-savy people. For that, it'll take some more time to turn that into a specter-extension.

**Comment by moneymanolis** [comment]
@Odellian SPV is not really an option for us, since you have no mempool with SPV nodes, so no fee estimation and 0 confirmations (aka pending incoming transactions) can't be handled. 

You could also put your onion address of your node in the Specter settings of your friends & family, so they would use your node as a backend. This is, however, rather slow, but works. You could give it a go. 

If you want to send some sats: This is the [link](https://donate.specter.solutions/apps/3k77BAT6zshCGNd3i7gw9WKwXQy1/pos)

**Comment by k9ert** [comment]
As we're definitely not planning to implement SPV in the strict sense but rather the connection towards (different) electrum-nodes which you need to trust more or less, i'll close this issue.
