### ISSUE TITLE
UI Improvement needed:  Transaction history added/substracted amounts unclear

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1861]
Receiving, sending and self transfers all show up as white amounts:
![image](https://user-images.githubusercontent.com/60378539/187044298-3f6a728d-dd0f-47b6-8093-2ad471809e49.png)

It is completely unclear what is added or subtracted from the wallet.  I propose a more typical (like electrum or bitcoin core) style formatting of the numbers:
![image](https://user-images.githubusercontent.com/60378539/187044376-75065692-6ef5-4190-bc5c-2f64e5fc78f5.png)

1. Self-transfers should show the fees lost.  
2. added amounts should be in default color (optional is a +)
3. sent/subtracted amounts should be red to be consistent with any sensible book-keeping formatting

I think this is extremely important for readability. @k9ert , @moneymanolis  What do you think?

**Comment by moneymanolis** [comment]
Shouldn't sends also include the "fees lost"? @relativisticelectron

**Comment by k9ert** [comment]
Ok, i've started to work on this. For now i will ommit the coloring but there is enough left:
* The amounts are sometimes not properly calculated. At least if you have txs which have inputs not coming from the wallet
* The amounts should not only be negative for outlow, they also should have a different meaning in the utxo-view: There, you're only interested in the `utxo_amount` of the utxos rather than the `flow_amount`. Those two terms will get new keys in tx-jsons and also will be used in the header of the table.

**Comment by k9ert** [comment]
For the reference: https://github.com/cryptoadvance/specter-desktop/releases/tag/v1.14.5
