### ISSUE TITLE
v2.0.0-pre6: Save Backup PDF doesn’t work. 

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#2143]
- When Wallet was added, the download of the Backup pdf doesn't work. Not clickable. Doesn't react.

![image](https://user-images.githubusercontent.com/47259243/216223632-f4e4b182-8ed3-4975-9147-aa22ac20e733.png)

**Comment by Shivoham102** [comment]
Hey, I'm new here and want to solve this issue.

**Comment by Shivoham102** [comment]
I think the problem is that there is no Roboto fonts in the fonts folder
![image](https://user-images.githubusercontent.com/66953222/216354483-2e467461-c911-4024-a043-ae262d2599c2.png)

After adding the fonts to the folder this is the only error that's thrown
![image](https://user-images.githubusercontent.com/66953222/216354808-d8324180-34b9-467f-94bc-e795a92f26ae.png)
