### ISSUE TITLE
pyinstaller build instructions don't work?

### ISSUE THREAD

**Issue by mflaxman** [cryptoadvance/specter-desktop#283]
I'm trying to follow these instructions:
https://github.com/cryptoadvance/specter-desktop/blob/2575aed4ada2e99c8cad95c0c1b6248890c1baa2/pyinstaller/README.md#L3

I'm running master @ 5cc92c989f6d071da6d936c06e0ba5629f03b7ce on MacOS 10.15.5
```
$ pyinstaller --onefile specterd.spec
63 INFO: PyInstaller: 4.0
63 INFO: Python: 3.7.8
71 INFO: Platform: Darwin-19.5.0-x86_64-i386-64bit
79 INFO: UPX is not available.
spec "specterd.spec" not found
```

I've never used pyinstaller and am just poking around. What I'm really interested in is if a compiled binary can be released (something that doesn't require someone to know how to use the command line).

**Comment by ben-kaufman** [comment]
Hi, according to the error, the most likely thing is that you're running pyinstaller from the root directory of the project instead of the `pyinstaller` folder, did you enter it (`cd pyinstaller`) before running the command? (Maybe we should mention this in the README...) 
As for release without the need to know to use the command line, the current builds we have already can be run without really using the command line (just double-clicking on it should be enough), but we are also working on #273  (demo: https://twitter.com/_benkaufman/status/1292547881006751749?s=20) which will turn this into a semi-desktop app with normal installation (.dmg, .exe tec.).

**Comment by mflaxman** [comment]
I just submitted a (very minor) to make the documentation clear.

#273 is very exciting! Spectre is great, but CLI is unfortunately too hard for 99% of bitcoin users :(
