### ISSUE TITLE
macOS: First launch hang?

### ISSUE THREAD

**Issue by janoside** [cryptoadvance/specter-desktop#329]
Just installed v0.7.2 from dmg on macOS. After startup I was shown the local/remove server preferences box. Chose local. Red ghost icon shown in the menu bar. It showed that the status was "Starting up Specter daemon..." for 2+ hrs (I launched just before stepping away from computer). No other status was given to indicate what was happening. When I returned to computer 2+ hrs later, I hit "Exit" and restarted and was immediately shown the UI. Sadly I can't offer any further debugging info since I wasn't shown anything.

**Comment by ben-kaufman** [comment]
Hi. Yes we are aware of this issue, which is likely unavoidable as it is due to Apple's "Gatekeeper", which blocks the app on the first launch if it is not signed and notarised by Apple.
We have mentioned it in the release (see "Note for MacOS" https://github.com/cryptoadvance/specter-desktop/releases/tag/v0.7.2). Basically from the second launch it should work properly.

What we could also do is on the first launch add a note/ popup with this note on macOS, which will probably make this clearer.

**Comment by janoside** [comment]
Thanks for that explanation. Read some of the docs but I missed that part. I definitely like the note/popup idea.

**Comment by ben-kaufman** [comment]
Cool, so I'll close this issue after adding that.

Ideally, we would've done the notarization, but it seems like Apple is unhappy with how our project is structured and so even if it's possible to get them to approve us, which I'm not sure it is, it'll take a lot of time and changes, so, for now, we'll have to make do with notifying about it...

**Comment by ben-kaufman** [comment]
Hopefully resolved by #370 so closing this for now.
