### ISSUE TITLE
Improvement: Creating a "new" wallet with existing txs has resyncing challenges

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#34]
## Problem:
Create a wallet in Specter that already has txs (e.g. an already-used Ledger Segwit wallet).

Initial balance will show 0 txs, 0.0 value.

Manually running `bitcoin-cli -rpcwallet=specter/my_new_wallet rescanblockchain (from block height)` will identify some of the early txs but it looks like the node's internal wallet just doesn't have many pre-computed addresses stored for that new wallet so it misses all txs after the first n (6?).

_By comparison Electrum wallets are generated with something like the first 1000 or 2000 addresses._

## Current workaround:
In the specter UI keep requesting "new" receive addresses until the last used receive address appears (the Specter UI will say that each addr is unused, but you'll have to compare against your known receive addrs from your previous txs that happened before importing into Specter).

At this point the node's wallet is aware of all of those receive addrs. Now run `rescanblockchain` manually as listed above and the txs will be found and will become visible in Specter.

## Solution:
* Generate many more addresses in the node's version of the wallet upon wallet creation.
* Add a "rescan from" block height option in the UI and pass that on the backend to a `rescanblockchain` call for that wallet.

**Comment by k9ert** [comment]
> Generate many more addresses in the node's version of the wallet upon wallet creation.

In order to keep it simple and effective, wouldn't it be better to provide a check box when creating the wallet "This wallet contains existing history" in order to create more addresses.

The rescanning feature needs the knowledge of the user since which blockheight he's using his device but i guess that's ok.

**Comment by kdmukai** [comment]
Agreed. I guess a two-step option would make the most sense:

* Has history?
    * If so, enter earliest block height/date OR leave blank to rescan from beginning of time.

A full rescan on my raspi4 took about 25min. Not great but not horrible either.

**Comment by stepansnigirev** [comment]
Yes, rescanning is challenging...
I think by default we should rescan from the first segwit-enabled block as we are working only with segwit wallets, it will save some time.
Also this request may take some time and RPC client can timeout easily. 
With master branch of bitcoin core rescan is very fast. 
@kdmukai , are you running latest release of bitcoin core or compiled it from master on you Pi?

**Comment by kdmukai** [comment]
Not yet. Still on 0.18.1 at the moment.

From what I've seen a rescan totally blocks Specter Desktop's access to the wallet until it's complete.

**Comment by stepansnigirev** [comment]
I wonder what happens if we call rescan via json-rpc and it times out. Will it stop rescanning or continue?
0.19 was released recently so we can switch to it. 
Can you check how fast is rescan on your Pi with 0.19?
If it's done in a few minutes we could block the interface for this time.
It also simplifies the number of addresses imported with `importmulti`.
For 0.18 I was setting a small limit for addresses because for large number of addresses it took forever. I think it makes sense to change the behaviour and import ~1000 addresses from start.

**Comment by stepansnigirev** [comment]
Should be solved by https://github.com/cryptoadvance/specter-desktop/pull/73
By default blockchain is not rescanned, keypool is 20 addresses.
In wallet settings you can add more addresses to the wallet and start rescanning blockchain.
It happens in the background and progress is visible on the sidebar and in settings.

**Comment by stepansnigirev** [comment]
So #73 was merged some time ago and now you can increase the keypool and trigger rescan from wallet settings, no i suppose we can close this issue.
