### ISSUE TITLE
Error In Ubuntu

### ISSUE THREAD

**Issue by urza** [cryptoadvance/specter-desktop#356]
Hello, when I try to run the latest release in Ubuntu 19.04 I get the following error:

```
./Specter 
Traceback (most recent call last):
  File "specter_desktop.py", line 7, in <module>
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /tmp/_MEImECdQ8/libnspr4.so)
[4144] Failed to execute script specter_desktop

```

I tried to sudo apt update and upgrade with the same result.
Any ideas how to fix this?
Thanks
urza

**Comment by stepansnigirev** [comment]
Oh, probably because we compiled the desktop app on Ubuntu 20, next time we will use an older version (probably 18 or so).

Can you try installing libc6 for now?
```sh
sudo apt-get update
sudo apt-get install libc6
```

**Comment by urza** [comment]
So it seems that Ubuntu 19.04 has officially ended on libc6 v 2.29
So I would either have to install it from other sources or upgrade to Ubuntu 20.

Anyway I am not a python developer, but isn't there a way how you could compile the app to native binary that contains all dependencies linked in a self contained package? I imagine if you get popular you will see a lot more issues like this..

**Comment by stepansnigirev** [comment]
Packaging in python is a bit complicated... 
v0.7 was the first release where we tried to package Specter into binaries, so it's pretty new to us.
We will get better at this in the next releases =)

**Comment by jlopp** [comment]
Same problem on PureOS (Debian)

```
$ sudo apt-get install libc6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6 is already the newest version (2.28-10).
```

**Comment by stepansnigirev** [comment]
We'll try to fix it in the next release (planned in a few days), for now you can try installing specter with pip (python 3.7+ is required, see main readme)

**Comment by stepansnigirev** [comment]
@k9ert what Ubuntu version are we using to build binaries on Linux? We may need to use v 18.
Pyinstaller docs recommend building binaries "on the earliest available version"...

**Comment by ChineseGeek** [comment]
I had a similar issue trying to run it in Bunsenlabs (Debian 10).

`[2312]` `Error loading Python lib '/tmp/_MEI5qe5jS/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version` `GLIBC_2.29' not found (required by /tmp/_MEI5qe5jS/libpython3.8.so.1.0)`

**Comment by k9ert** [comment]
> So it seems that Ubuntu 19.04 has officially ended on libc6 v 2.29
> So I would either have to install it from other sources or upgrade to Ubuntu 20.
> 
> Anyway I am not a python developer, but isn't there a way how you could compile 
> the app to native binary that contains all dependencies linked in a self contained 
> package? I imagine if you get popular you will see a lot more issues like this..

It's not that anyone has to downgrade because we're compiling on a older system. 
It's also not that you would older symbols then you could use because your version is newer than the one which it has been compiled with. The glibc is very special in this regard. Read up on it here:

https://developers.redhat.com/blog/2019/08/01/how-the-gnu-c-library-handles-backward-compatibility/

So the recommendation is indeed to use an old glibc for compiling. Obviously we need to somehow trade that of with other requirements.

We're currently reworking the way binaries get build, automate everything! Currently the release is built on:
[https://github.com/cryptoadvance/specter-desktop/blob/master/.gitlab-ci.yml#L3](registry.gitlab.com/cryptoadvance/specter-desktop/python-bitcoind:v0.19.1). The Dockerfile for that is here:
https://github.com/cryptoadvance/specter-desktop/tree/master/docker/python-bitcoind

which points to [python:3.8](https://hub.docker.com/_/python?tab=description) which is based on debian. These images has the same digest than buster (see tags tab).

Debian buster has [glibc 2.28](https://packages.debian.org/source/buster/glibc)

As far as i understand this, all of the people commenting here would be happy with the new release.

**Comment by k9ert** [comment]
This is currently blocked as the Linux binary generated automatically is not executing properly #373. Please stay tuned.

**Comment by valendin** [comment]
Same issue here, Ubuntu 18.04.5.

**Comment by k9ert** [comment]
We have a prelease:
https://github.com/cryptoadvance/specter-desktop/releases/tag/v0.7.3-pre3
Maybe you can check that this issue is fixed?

**Comment by thermalCat** [comment]
Yep. That fixes it for me. (linux mint 19.1)

**Comment by stepansnigirev** [comment]
Should be fixed now. Reopen if it's not the case.
