### ISSUE TITLE
New Feature: Optionally label utxos for enhanced utxo management and privacy

### ISSUE THREAD

**Issue by kdmukai** [cryptoadvance/specter-desktop#39]
First of many related privacy-focused utxo features.

Labeling utxos is step one toward better privacy management. Following the lead of Electrum, Wasabi, etc.

**Comment by stepansnigirev** [comment]
Great, labeling and managing inputs when constructing transactions are very desirable features.
How should we work with labels? 
To display them we can add a field in the history page. I am afraid that the table will become very dense then. Should we display a label instead of txid, add "tx details" screen and move txid and block explorer link there?
It would also make sense to add "search by label" feature.

**Comment by kdmukai** [comment]
Right, displaying the tx hash really isn't necessary for that screen. Even the address becomes way less important once labeling is instituted, though it can still be helpful to at least show the first couple chars (maybe 8 for native segwit?).

I went through this trying to label my historical txs that were imported into Electrum. Having date and addr displayed makes it quicker and easier to match up records.

**Comment by stepansnigirev** [comment]
#94 #95 implemented utxo view and labeling
