### ISSUE TITLE
v1.2.3 tag

### ISSUE THREAD

**Issue by ZeroPointEnergy** [cryptoadvance/specter-desktop#399]
I saw this version appear and vanish multiple times now. I wonder what's going on with this? Local tag that gets accidentally pushed?

**Comment by stepansnigirev** [comment]
@k9ert is trying to make automatic build of binaries...
Real release will be tomorrow.

**Comment by k9ert** [comment]
Yes, that was triggered by me and it happened more than once because of several reasons playing into each other with that astonishing effect:
* We're using gitlab for release builds (and travis-CI for PR builds) and we have therefore 4 different repos: the original and my fork each once on github and once on gitlab with synchronizing-rules
* If a release-binary got uploaded on github, it creates automatically a new tag on github which get synchronized to gitlab
* Gitlab seems to have some strange rules for retriggering a build when a tag is still there but the build related to that tag cot canceled
* Github doesn't have the possibility to create API-Keys allowing upload of release-artifacts which are bound to a specific project on Github
* i'm currently testing the automatic release and at least once the binary created on my gitlab-project was created on the original-repo (creating a tag which got triggered yet a build)

Conclusion: This should not happen again, no matter of the above circumstances, because 
* i deactivated the API-key on my gitlab-project (and the upload is now well tested, so no need to have that again). 
* Apart from that i systematically purged that tag on all 4 repos.

Sorry for the confusion.
