### ISSUE TITLE
Research: Specter and multisig pitfalls

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#44]
Kaspar Etter from Shiftcrypto wrote a quite interesting article here:
https://medium.com/shiftcrypto/the-pitfalls-of-multisig-when-using-hardware-wallets-9b0e98e4c19c

Roughly three topics where covered and they checked these three topics against coldcard, Ledger and Trezor and created responsible disclosures with their findings.

Specter should selfcheck against these topics mentioned there. For that the different topics need to be understood and checked with Specter. If we have findings, we should create new issues out of that.

Research wanted!

**Comment by stefanwouldgo** [comment]
When sending from a specter multisig, as pointed out in the article, ledger simply displays both the target address and the change address. Specter could show the change address, but this wouldn't be secure either, because these attacks assume the computer (i.e. Specter) is compromised and could show you any change address. So I really don't see anything specter could improve here, displaying the correct change address would just give false confidence to the user.

Coldcard seems to correctly check the change address (if it knows the multisig in question). So maybe spectre should caution the user to always control at least one coldcard that can check for the correct change address.

**Comment by stepansnigirev** [comment]
Ledger is always the weakest point of the multisig setup... Too bad, especially taking into account that their hardware is the most secure across the hardware wallets...
I see two ways to work around this issue:
1. Use a separate device that can verify change addresses of the multisig transactions, or rely on the other hardware wallets to verify change address
2. Write a new Bitcoin app for Ledger or make a PR that would allow change verification for multisig.

Coldcard and Trezor can verify change addresses in multisig if xpubs of cosigners are provided in the transaction. We do it for ColdCard in PSBT, but for Trezor it is not yet supported in HWI.

**Comment by llxado123** [comment]
Cobo Vault can directly show multi-sig receiving & change address now. And even without xpubs of other co-signers(which can be swapped by hacker), Cobo Vault can still verify the change address. It's designed as not stateless.

**Comment by stepansnigirev** [comment]
@llxado123 is there a way to verify the address on the device by scanning it's QR code?
I think scanning the address is more convenient than browsing through the whole list of addresses on the device, might be a good addition for Cobo.
