### ISSUE TITLE
Tor support

### ISSUE THREAD

**Issue by NicolasDorier** [cryptoadvance/specter-desktop#483]
I got this request of a user of BTCPay wanting to use his own full node with specter.

https://github.com/btcpayserver/btcpayserver-docker/pull/377

Sadly, we can't merge that as BTCPay's full node has some well known fixed password, so exposing RPC on internet is a very bad idea.

However, we are exposing RPC through a TorV3 QR Code / URL, which FullyNoded use for example. This include all info to connect to RPC.

**Comment by ben-kaufman** [comment]
Hi, we are already supporting Tor RPC connection since v0.8.0.
I was even able to test it myself and connect my locally running Specter to my remote BTCPayServer instance.

It would be nice if BTCPayServer would have a Specter desktop supported icon like it does there for Fully Noded.
Also would be helpful to see the data needed in a clearer format (username, password, Tor url) so it's clearer for users wanting to connect to Specter. (You can currently see the final URL format but this is unclear to input unless you know how it works)


Btw (unrelated), I was wondering if BTCPay server supports using descriptor for receive address generation?

**Comment by NicolasDorier** [comment]
Hey @max302 what you want already work.

@ben-kaufman great idea, can you make a PR and add yourself here https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Views/Server/RPCService.cshtml ?

We should make a new release in max 3 weeks I expect.

Yes, I expect adding descriptor support in BTCPayServer.
Not in the near term (in more than 1 month). I need to review and merge https://github.com/MetacoSA/NBitcoin/pull/696 and add support to NBXplorer.

**Comment by NicolasDorier** [comment]
@max302 seems to try to make specter work as a web app, if so the integration will be even easier. (It would be similar to Ride the Lightning, directly bundled)

**Comment by NicolasDorier** [comment]
Closing this issue, as right now it is already possible to use specter via Tor.

**Comment by ben-kaufman** [comment]
Thanks @NicolasDorier I'll make a PR to add that next week probably.

Having it directly bundled would be great! @max302 let me know if you need help doing that.

**Comment by max302** [comment]
@ben-kaufman I got the docker image working yesterday, should get it done and tested by end of week.

**Comment by NicolasDorier** [comment]
@ben-kaufman I will do today, we will release a new version today.

**Comment by NicolasDorier** [comment]
![image](https://user-images.githubusercontent.com/3020646/95421815-23b9bd00-0979-11eb-81f4-9097ca83dc30.png)
