### ISSUE TITLE
Address Labels not recovered in Wallet restore

### ISSUE THREAD

**Issue by jimmysong** [cryptoadvance/specter-desktop#603]
Steps to reproduce:

1. Label an address in a wallet
2. Backup the wallet
3. Restore the wallet in a new instance of Specter
4. Look at the address, it doesn't have the label from 1

**Comment by stepansnigirev** [comment]
If you export only the wallet from wallet settings then it has only minimal info: blockheight of the first tx and the descriptor.
If you use full Specter backup (available from general settings) then you can recover labels as well (at least in the latest version), but this backup includes all the wallets and devices, so you probably don't want to share it with other people.

We could include the labels in the json file for the individual wallet, but for QR code or copy-paste I would keep it without labels, otherwise QR code will become too big.

**Comment by jimmysong** [comment]
I did this using the general settings and the address labels didn't get restored.

**Comment by stepansnigirev** [comment]
Oh, ok, then it's a bug. We'll check... Thanks!
