### ISSUE TITLE
[security] Onion addresses are not secret. They are public.

### ISSUE THREAD

**Issue by qertoip** [cryptoadvance/specter-desktop#632]
[Running Specter Desktop over a Tor hidden service](https://github.com/cryptoadvance/specter-desktop/blob/master/docs/tor.md) claims that onion address Specter generates is secret and "only known by you".

This is false as Tor onion addresses are not secret. They are all indexed and public by design. The "Hidden" in the name considers hiding the IP address serving the onion.

It seems authentication is simply missing.

**Comment by stepansnigirev** [comment]
You can enable authentication in the Settings - Authentication tab. But you are right, we should edit the docs.

**Comment by qertoip** [comment]
Thanks a lot for the prompt answer! It feels like authentication should be obligatory. It doesn't make sense otherwise, except maybe for developers or debugging.

**Comment by stepansnigirev** [comment]
It depends.
On my local PC that doesn't expose Specter to the internet I don't use authentication because only I can access it.
On my VPS I use simple authentication by NGINX because I don't want people to know that I am running Specter there, and it's obvious what is running there if you see Specter-specific login page.
I would probably enforce people to use authentication if they want to enable Tor.

**Comment by qertoip** [comment]
>  I would only force people to use authentication if they want to enable Tor.

Yes, this is exactly what I had in mind. Thanks!

**Comment by stepansnigirev** [comment]
I opened an issue on the implementation here https://github.com/cryptoadvance/specter-desktop/issues/634
