### ISSUE TITLE
Dates of transactions are all the same

### ISSUE THREAD

**Issue by BTCBellyButton** [cryptoadvance/specter-desktop#680]
14/11/2020 is when I added the wallet (ledger) to Specter. Some of those in the screenshot are from 2017 and after:

![image](https://user-images.githubusercontent.com/68573637/99888725-7216d880-2c14-11eb-9cbd-d3764298f776.png)

![image](https://user-images.githubusercontent.com/68573637/99888774-cb7f0780-2c14-11eb-99b4-a5a724b9cd42.png)

**Comment by ben-kaufman** [comment]
Strange, I thought we solved that already... Are you on version v0.10.0?

**Comment by BTCBellyButton** [comment]
Yep. 0.10.0, Ubuntu 20.04.1

**Comment by BTCBellyButton** [comment]
I also re-scanned the blockchain just in case but the dates are still all the same.

**Comment by stepansnigirev** [comment]
This is a very strange bug of Bitcoin Core, it somehow returns the time of rescan instead of the time of the block, even though we are currently taking a minimum of all the times returned by Core - blocktime, time and firsreceived.
We could ask Core for block headers and determine the time from that, but it would mean many RPC calls again.
Alternatively, we could fetch time of a few blocks and calculate estimated time from that, not sure yet.

**Comment by k9ert** [comment]
For the reference most probably this one: https://github.com/bitcoin/bitcoin/issues/20181

**Comment by BitcoinTsunami** [comment]
As a specter user, I had the same problem with multiple incorrect date across several wallet.

I've look at the Bitcoin Core code and the function ComputeSmartTime in wallet.cpp attire my attention.
The algorithm try to search for the best time between the received one, the block time one and a smart one wich is produced by a lot of time corrections. 
This ComputeSmartTime method is conceived with a real time approach in mind.
The technique used to determine the smart version of the time is based on the hypothesis that you can't discover transactions in the wrong order.
And if you suppose that transcations can be discovered in the wrong order, the lastestEntry variable is going to be wrong for every transactions discovered after and be the exact same date.
That's exactly what I saw in my Bitcoin Core wallet, a lot of transactions with the exact same date, which is incorrect.

I've not found yet a simple example where transactions could be dicovered in the wrong order, but I'm looking for a case where you start with a small rescan and after a larger one.
To be more precise : if you rescan only the latest part of the history (2020 year only), and proceed to a larger rescan after (full rescan),
every transaction before 2020 will be noted in 2020 du to the lastEntry constraint in nTimeSmart = std::max(latestEntry, std::min(blocktime, latestNow));

When you think about it, in a rescanning scenario, the blocktime is the only exploitable time. The received one means nothing and you can't find a better value.

That's why I've patched the problem like this :
- add a rescanning_old_block boolean to ComputeSmartTime
- In case of rescanning_old_block don't use anything else than blocktime.
- propagate this boolean in the methods hierarchy to differenciate realtime incoming transactions with rescanning case.

I'm currently testing my patch. Tests cases stay all green. If everything is repaired in my wallets,
I'll submit this little patch in another comment to get feedback on it.

**Comment by BitcoinTsunami** [comment]
Hi I've proposed a patch for Bitcoin Core (https://github.com/bitcoin/bitcoin/issues/20181 thread)

From what I've seen, you can't correct date after bad transaction date determination.

If you dont want to wait for an update (It will be long because event if it's a Bitcoin Core bug, Bitcoin Core is unaffected without API interraction from external tools, like specter) :
- patch Bitcoin Core with my patch and run it
- backup you specter wallet
- destroy your specter wallet
- import your backup.
- revert to a standard Bitcoin Core version.

Important : you don't need to keep up the patched version. Incorrect date determination is only due to the rescanning process.

**Comment by BitcoinTsunami** [comment]
I've debug specter desktop to understand why my wallet induce this bug with Bitcoin Core.

Here's what I've discovered :
In my case, the trigger of the bug is in my specter backup. In the wallet JSON file, the blockheight field is set incorrectly high. That's why when I restore my wallet, the first rescanning process of Bitcoin Core ignore my oldest transactions (because Specter ask for a too recent blockheight as startpoint).
When I relaunch the rescanning process from the first segwit block, all my transactions are found, BUT the oldest transactions have incorrect timestamp. This last part is not specter fault, because the rescanblockchain RPC function of Bitcoin Core don't specify any restrictions in the documentation. But in practice if your start with a small rescan process (smaller than you transactionnal range) and you relauch a bigger one, Bitcoin Core will badly determine transaction time (due to a bug). Moreover, you can't fix it later, because the rescanning algorithm of Bitcoin Core only look at new transaction and never reevaluate the transaction time of an already known transaction.

Conclusion :

Specter as badly determine my blockheight in my backup (several wallet impacted) and that's the root cause of the bad rescanning sequence, but it's not the case anymore in the latest version. It may be a ripple effect of bad transactions order in an older version of specter.

Finally it's really easy to fix for user impacted like me. You don't need the modified Bitcoin Core version.

- backup you specter wallet
- destroy your specter wallet
- edit your json wallet and fix you blockheight with an older one than your first transaction
- import your backup.

I've tested it with a standard Bitcoin Core v0.21rc2. Even if there is a bug int Bitcoin Core, you can avoid to trigger it that way.

**Comment by ben-kaufman** [comment]
Hi, thanks a lot! Really great work finding the issue!!

Yes until the latest version I believe (not sure since which one though), we had an issue where the start block for rescanning from import wallet was wrong.

Regarding the issue, I was able to successfully reproduce it the way you described, and now made a "fix" to use the blocktime in the transaction history screen when the dates of the txs are wrong.
I think if you can confirm that works for you, we could close the issue here and just continue with the issue in Core as possible.

**Comment by BTCBellyButton** [comment]
Trying the procedure 

> Finally it's really easy to fix for user impacted like me. You don't need the modified Bitcoin Core version.
> 
> backup you specter wallet
> destroy your specter wallet
> edit your json wallet and fix you blockheight with an older one than your first transaction
> import your backup.

with 0.20.1 and it seems to be working for me as well.

**Comment by k9ert** [comment]
Can we keep that open until we have a link in the troubleshooting part of the FAQ?
I think this is high likely that others are impacted by this as well?! Might be wrong here, then simply close it agian!

**Comment by ben-kaufman** [comment]
I think we could probably close since now this shouldn't be a problem anymore - if the transactions we get from Bitcoin Core are affected by this we will now just display the blocktime instead - which is always correct. So I think we could close this here unless you think we should leave it open anyway?
