### ISSUE TITLE
Version 0.10.1 for Windows doesn't start

### ISSUE THREAD

**Issue by BTCBellyButton** [cryptoadvance/specter-desktop#711]
I tried to install the new Windows version and, also after uninstalling it and install it again, this is what happens:

![image](https://user-images.githubusercontent.com/68573637/100519695-438e8580-315f-11eb-8ed6-a30f581bf466.png)

I re-installed the previous version 0.10.0 that connects to my Ubuntu node with the 0.10.1 running and it shows 0.10.1 from windows.
Ubuntu: 0.10.1 running
Windows: 0.10.0 installed, shows 0.10.1
![image](https://user-images.githubusercontent.com/68573637/100519886-5786b700-3160-11eb-8d73-240326e3380b.png)

**Comment by eigentsmis** [comment]
Same here - v0.10.1 doesn't start on MacOS High Sierra

**Comment by ben-kaufman** [comment]
Hi @eigentsmis , yes currently High Sierra isn't supported for the desktop app, but should work well from pip. Hope in the next release we will manage to make it work for such older macOS versions but can't be sure.

@BTCBellyButton is that still happening with v0.10.2? Also what happens if you try to restart Specter? Same issue?

**Comment by BTCBellyButton** [comment]
I skipped the 0.10.2 and just upgraded to 0.10.2.
Problem fixed!

Thanks!
