### ISSUE TITLE
[Privacy] prefill hardcoded blockexplorer in settings for clarity

### ISSUE THREAD

**Issue by openoms** [cryptoadvance/specter-desktop#718]
To reduce unsolicited outside calls the `Block explorer URL (main):`
![image](https://user-images.githubusercontent.com/43343391/100549622-ed5b3880-326b-11eb-97b8-b41eef6f9c2b.png)
should be prefilled with the hardcoded blockstream.info value:
https://github.com/cryptoadvance/specter-desktop/blob/4fd68f88313abc2a4bb5dbacb966bef5fd20cf23/src/cryptoadvance/specter/specter.py#L532

This way there would be a single place to disable (delete) the setting.

When importing the backup on a pruned node all wallets had this box checked by default:
![image](https://user-images.githubusercontent.com/43343391/100549697-6a86ad80-326c-11eb-9624-34c7d57e0885.png).

Related merged PR: https://github.com/cryptoadvance/specter-desktop/pull/344
open: https://github.com/cryptoadvance/specter-desktop/issues/408

Also interested in the https://github.com/Start9Labs/btc-rpc-proxy-wrapper)
(mentioned here: https://github.com/cryptoadvance/specter-desktop/issues/298#issuecomment-724137049)

**Comment by ben-kaufman** [comment]
In PR #756 I made it so that for the pruned node block explorer you'll have a text field (pre-populated with your default explorer),   where you can edit the explorer URL used for the specific fetch. So I think we can say now the block explorer in the settings is really not used for any data fetching. Does that solve this issue?

**Comment by openoms** [comment]
@ben-kaufman yes, thank you for sorting thisout. Closing.
