### ISSUE TITLE
Ledger Nano S not detected for display address on device

### ISSUE THREAD

**Issue by starsoccer** [cryptoadvance/specter-desktop#751]
Attempting to display a multisig address on my ledger nano S device does not seem to work. It tries to find the device but appears to never find it, Ive tried having the bitcoin app open as well as not and in either case it is not detected.

Specter is able to detect my device when being used as a device and successfully get its xpub information

**Comment by ben-kaufman** [comment]
Hi, Ledger devices don't support multisig verification and are therefore not recommended (though still possible to use) as part of a multisig setup. This is not something depending on Specter but on Ledger's firmware, so since we can't really do anything about that on our side I'm closing the issue (please feel free to reopen if you see a reason to).

**Comment by starsoccer** [comment]
Noted, it wouldd be useful if this was show on the software like if you click display address and it detects a ledger connected as the only device to show a popup stating this.
