### ISSUE TITLE
Cobo can't scan Specter's QR codes.

### ISSUE THREAD

**Issue by Transisto** [cryptoadvance/specter-desktop#795]
Is Cobo only supported via PSBT files?
https://github.com/CoboVault/cobo-vault-cold/issues/269

**Comment by ben-kaufman** [comment]
Hi, from which screen of the Cobo are you trying to scan the QR?

**Comment by Cheburashka-gena** [comment]
I've had this problem as well. I figured it's because of my laptop since it's very old and has a crappy webcam. From what I recall it was when signing a transaction. You have to scan a QR code with the webcam off of the Cobo. You can either choose a normal image or an animated one. I had to try it for like 10 minutes to get a successful scan.

Now I'm seeing others are having this problem, so here's hope that it's not just my old crappy webcam.

**Comment by IsaacJ1** [comment]
Hello, I was having this problem. The issue was that I created the wallet on Specter with the Cobo Vault set to Electrum wallet. Cobo instructions state that the wallet should be created with device set to "generic". You may want to set your device to "generic and see if that helps.

**Comment by ben-kaufman** [comment]
You mean on Specter? You could just set the device to "Cobo Vault" no?

**Comment by IsaacJ1** [comment]
Yes. The Cobo Vault must be set to "generic wallet" when you create or import device to Specter.  I mistakenly had set to Electrum and I had a lot of trouble with the scanning. Once I created or imported the Cobo set to "generic" everything worked perfectly.

**Comment by Transisto** [comment]
Thanks that was exactly it, Need to be generic I was on Electrum thinking electrum was somewhat standard.
