### ISSUE TITLE
v0.11.0-pre3: Cannot create any wallets

### ISSUE THREAD

**Issue by instagibbs** [cryptoadvance/specter-desktop#813]
Clicking "Create wallet" does nothing. Works on v0.10.4 correctly.

Trying on OSX, can test on Linux later if needed.

**Comment by ben-kaufman** [comment]
Strange, just tried on MacOS, works fine for me. We also have a test for that in our testing framework which is passing fine too.
Maybe it's related to something more specific in your setup, which OSX are you using? Also if you could check on Linux that'd be very helpful too.

**Comment by k9ert** [comment]
Where do you click exactly? I could make assumptions and they are probably right but making assumptions is always bad in troubleshooting process. What version of OSX are you using exactly? 
Maybe you can create a screenshot similiar to this one (this is what happens if i click on "create wallet"). Please activate the dev-tools before, switch to the network-tab and clear the list.
![image](https://user-images.githubusercontent.com/117085/103203371-0996d780-48f5-11eb-8592-67b9a2000f58.png)

**Comment by instagibbs** [comment]
@k9ert the "Create wallet" button. It just does nothing, no reaction.

@ben-kaufman Happens on mainnet and regtest. Don't have a ton of time to debug but I'm willing to run any proposed fixes :+1:

**Comment by ben-kaufman** [comment]
@instagibbs , can you please check out #817 ?

**Comment by ben-kaufman** [comment]
Reopening until @instagibbs can confirm it solves the issue

**Comment by instagibbs** [comment]
seems to fix it, thanks!
