### ISSUE TITLE
Continuous Loop to reenter passphrase when adding new Trezor or Keepkey device

### ISSUE THREAD

**Issue by neurofighter** [cryptoadvance/specter-desktop#877]
When you add a new Trezor or Keepkey device that has passphrase enabled, Specter begins a continuous loop of asking you to enter your passphrase after you enter your pin.

**Comment by ben-kaufman** [comment]
This is due to a change Trezor did a few months ago to fix a security issue with how they handle the passphrase. Now they require to manually approve the passphrase for every action done with the device. For signing this is fine, but for setup - where we extract xpubs, that means quite a lot of confirmation clicks. Can't really do much on Specter side for that, it's just an inconvenience in the setup but after that shouldn't be bad.
See #417

**Comment by neurofighter** [comment]
Oh so eventually it completes?  I assumed it would just keep repeatedly having me type in a passphrase into eternity

**Comment by neurofighter** [comment]
Aha you're right.  I guess you can close this one thanks!
