### ISSUE TITLE
Pending Txn is "Stuck" - Can't Spend UTXO

### ISSUE THREAD

**Issue by sahilc0** [cryptoadvance/specter-desktop#951]
Hey team, having an issue with a transaction from over a month ago. 

- Fee was too low so didn't get confirmed
- Cleared from the mempool (see blockstream.info, no txn)
- Specter hasn't cleared it yet so I can't recreate the txn with the same utxo
- RBF "Speed Up" doesn't work

Version:
- Currently 0.10.1 but this was happening on prev version as well
- Running on MyNode Raspi4, viewing on macOS

Any thoughts on how to fix this?

![Screen Shot 2021-02-15 at 5 09 28 PM](https://user-images.githubusercontent.com/8256062/108007521-0d6cdf00-6fb3-11eb-8521-213f98708198.png)
![Screen Shot 2021-02-15 at 5 11 09 PM](https://user-images.githubusercontent.com/8256062/108007527-1067cf80-6fb3-11eb-9141-f8eb3542500a.png)
![Screen Shot 2021-01-19 at 9 45 16 AM](https://user-images.githubusercontent.com/8256062/108007497-ff1ec300-6fb2-11eb-872b-07ebbfcddf19.png)

**Comment by ben-kaufman** [comment]
I'd suggest to try deleting the wallet and reimporting it. Have you tried that?

**Comment by kdmukai** [comment]
Would it make sense to add an "abandon" option and invoke `abandontransaction` (see: https://bitcoincore.org/en/doc/0.20.0/rpc/wallet/abandontransaction/)

**Comment by ben-kaufman** [comment]
@kdmukai yes that's a good idea. I think we could add a button for that in the transaction details popup if a transaction is unconfirmed.

**Comment by kdmukai** [comment]
I'll see if I can get to implementing it this weekend. I'm eager to get back to making contributions.

I'll also see if I can trap the RBF error noted above. At a minimum some more useful info would help. And ideally trigger a "Your tx has been purged from the mempool, ABANDON this tx so you can create a new tx for your utxo(s)" message with an ABANDON button.

**Comment by sahilc0** [comment]
Thanks @kdmukai <3
@ben-kaufman thanks man, FYI I am re-setting up my specter with Umbrel and downoading the chain from scratch so it'll be a while before I can update this thread with confirmation that the txn is still there

**Comment by kdmukai** [comment]
I've been working on a test case to validate the eventual solution. But, oof, it's a heavy lift!

@ben-kaufman @stepansnigirev @k9ert I could use some suggestions. I managed to set up a test where I spin up a new bitcoind so that I can set `-maxmempool` to its minimum of 5MB. I was also able to add a Bitcoin Core hot wallet so that I can sign txs and broadcast them.

Lots of rough edges, but at the moment my test case is successfully spamming 200 txs to its mempool:
https://github.com/kdmukai/specter-desktop/blob/abandon_tx/tests/test_specter.py#L46

The problem is that just to get that far it's taking 5 minutes on my M1 MacBook Air/16GB RAM and only filling up:
```
{'loaded': True, 'size': 200, 'bytes': 33200, 'usage': 240656, 'maxmempool': 5000000, 'mempoolminfee': 1e-05, 'minrelaytxfee': 1e-05}
```

So I'm only at 0.24MB in the mempool, right? Roughly speaking, if we want to hit the 5MB limit, that's ~100 minutes to run the test. Any ideas for how to make more bloated txs and save us some time?

I dabbled a bit to get a legacy m/44' wallet working but failed (I assume I screwed something up with the derivation path?). But I figured those transactions would eat up a little more space.

**Comment by k9ert** [comment]
@kdmukai  really appreciate your efforts here and also very happy to see you here again. As someone who is doing such stuff for some time i can feel with you as you took a case which is really quite to wrap in a testcase. I think we'll move now in a direction to do more testing in general and we probably will also catchup with old untested stuff a bit more.
Having to release 2 hotfixes within two days was something which you don't want to do but still it's much (MUCHMUCH) better than i've seen in other projects so far.

For concrete thoughts: I don't have a really good idea here but i think it might be worth lowering that 5MB to 1kB in bitcoin-core with the argument to make it easier to test. Allowing such kind of things are imho good/best practise and it's worth a try?!

**Comment by kdmukai** [comment]
@k9ert thanks! Wherever this test case ends up there are definitely some good reusable pieces in it to help build a more robust test suite.

As for the mempool, bitcoind won't start if you try to pass in a `maxmempool` size less than 5. 
```
$ bitcoind -regtest -maxmempool=1
Error: -maxmempool must be at least 5 MB
```

I did some ad hoc tests outside of the test case and just manually spun up regtest, made a test tx, stopped bitcoind, wiped out the mempool.dat, and started bitcoind up again. But when the wallet is loaded the node sees the pending tx and just adds it back to the mempool.

So I think I'll just have to simplify this test case to: create a tx, wire up Specter to call `abandontransaction` on it, verify that the tx is gone, and that Specter's wallet obj doesn't have any issues. But the actual Specter UI implementation flow would ideally still do a mempool sanity check ("wait, you can't abandon a tx that I still see in the mempool!" vs "Nope, that tx is nowhere to be found now").

Then since the real world bitcoin network is so congested now, I'll just throw a real tx on mainnet with the lowest possible not-yet-purged fee and hope it gets purged. Then verify that the "abandon" works as expected through Specter.

**Comment by kdmukai** [comment]
It occurred to me that I ought to see how Bitcoin Core does its mempool purge tests. They're also setting `maxmempool=5` but have some utility functions that should help us here:

https://github.com/bitcoin/bitcoin/blob/e49117470b77fb7d53be122c6490ba163c6e304d/test/functional/test_framework/util.py#L501

So maybe there's hope yet for this beastly test case!

**Comment by kdmukai** [comment]
OMG successfully filled the mempool in my test case! I was able to import and lightly modify the Bitcoin Core test case and related utils! Thank you, core!!! Now I can start the actual work of implementing an Abandon tx flow.

Though note: this required lots of copying-and-pasting from core. Any licensing or maintainability concerns @ben-kaufman @k9ert @stepansnigirev?

see: https://github.com/kdmukai/specter-desktop/tree/abandon_tx/tests/bitcoin_core

**Comment by k9ert** [comment]
Looks good! We have the exact same license so that's ok. Also no maintainability concerns at least from my side. Go ahead and thank you very much :-).
